### ISSUE TITLE
Provide generalized mechanism for Server to Server Monitoring Communication

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#153]
The active server must manage monitoring for all the passives in it's group.  Servers need a generalized mechanism for communicating state of servers, entities and services from passive to active.

**Comment by jd0-sag** [comment]
There is some question of the best way to pass these messages over the group channel but that should be resolvable with some internal experimentation.

The bigger questions are those regarding how this will be exposed and interact with other monitoring service implementations.  A few specific issues to resolve on this front (although these can be addressed, in the background, while the messaging layer experimentation is done):

1. What changes does this impose on the organization of the monitoring tree and best efforts push messages?  Specifically, does this exist as another level within that structure or is a different, purely-internal-facing, API?
1. If we plan on exposing this capability to passive-resident entities and services, how would we ensure that our "shim" implementation is selected over the externally-provided one?

One possibility to resolve both of these is to create a second interface for monitoring and split the responsibility of monitoring data between the existing and the new one.  Essentially, this would mean that the existing `IMonitoringProducer` interface would only be implemented by the server, itself, as a shim.  The externally-provided implementation would be of a slightly different interface which was explicitly told of the origin of its given data, in each call.  Most likely, it would have the identical shape, but only include a few additional arguments (as that is literally its meaning).

Another big question related to this is how to handle cases like passive fail-over.  The new active effectively needs to have the same data as the original (minus the now-defunct active), in order to be a correct and consistent view of monitoring data.

Minimally, this means that the active and all the passives need to see all data provided by any of the passive monitoring interfaces, so they can rebuild this information, no matter which one becomes the new active.  The "secondary interface" idea may simplify this, as well, in that it would remove the need for the shim implementation to cache any of this state in an intermediary form.  Instead, it could always pass the information it receives down to the externally-provided implementation for it to manage in its native form.

Getting back to the kind of data we would need to send over the wire, the source server and consumerID would be required for each of these messages (so they could be given context when passed to the externally-provided implementation).  In terms of the high-level data required, all node add/remove events would need to be provided, as they are defined as reliable, while the pushed events could be heavily throttled, as they are only defined as best-efforts.

**Comment by jd0-sag** [comment]
@anthonydahanne @mathieucarbou : You guys probably want to be kept in the loop on this one since I want to make sure that these ideas make sense to both of you, no matter how they evolve.

**Comment by jd0-sag** [comment]
Talked about this a bit further, this morning, and revised the plan in response to some problems Myron pointed out.  The plan for direction of the prototype:

- We will need to split out a "lower-level" interface which will exist below `IMonitoringProducer`.  Until we come up with a better name, we will call this `IStripeMonitoring`.  `IMonitoringProducer` will be provided as part of the platform implementation (much like `ClientCommunicator` or `IEntityMessenger`)
- `IStripeMonitoring` will have effectively the same interface as `IMonitoringProducer` except that each call will also receive a `source` parameter, describing the server where the call originated (type to be determined)
- `IMonitoringProducer` will continue to be the service entry-point used by entities while `IStripeMonitoring` will only be accessed, directly, by the server implementation
- passive servers will not use `IStripeMonitoring`, but will cache the data they are given in their `IMonitoringProducer` implementations
- passives will also copy all the data given to `IMonitoringProducer`, to the active of the stripe.  In the case of tree data, none will be lost.  In the case of best-efforts data, we will likely apply a static throttling heuristic (probably only 1 message per queue name per `X` time interval)
- upon promotion to active, the server will dump all its cached `IMonitoringProducer` data into the `IStripeMonitoring` implementation
- upon observing another passive being promoted to active, a passive will copy all of the data in its `IMonitoringProducer` to the new active
- active servers will receive any data sent by passive `IMonitoringProducer` and pass that into its local `IStripeMonitoring`, with the appropriate `sender`.  The `consumerID` will be used to make it appear as though the message is coming from the same entity (which also means data relating to now-deleted entities - since these could be racy - can be dropped by the server)

To sum up what data exists where:

- the data from any passive entity, passed into the passive's `IMonitoringProducer`, will be cached in its `IMonitoringProducer` implementation but also copied to the active's `IStripeMonitoring`
- the data from any active entity, passed into the active's `IMonitoringProducer`, will be passed directly into the active's `IStripeMonitoring`
- the active caches nothing in `IMonitoringProducer`
- the passive caches only its own data in `IMonitoringProducer` and does not use `IStripeMonitoring`

For the most part, it seems as though we should be able to expand the use of `PlatformInfoRequest` to accommodate this.

If this prototype works, we will need to define `IStripeMonitoring` and also change the declared monitoring tree content, for the platform, to no longer explicitly include data regarding other servers, since that will now be passed through this generic mechanism.

**Comment by jd0-sag** [comment]
Been working on prototyping this and it is requiring a substantial refactoring to how we register the initial services of the platform.  This is because this _shim_ monitoring service which hides the details of how to decorate the server's data for consumption across the stripe is being internally-provided, but sits on top of an externally-provided service (in order to back-end on externally-defined monitoring systems).

The details of how the passive-side data is handled is still somewhat complicated and may be further revised.  The design I am currently in the middle of prototyping:

- When in **active** mode, the _shim_ **caches no local data**, passing all local and remote data directly to the underlying implementation
- When in **passive** move, the _shim_ **caches locally-created data** but also passes all local and remote data to the underlying implementation
- Actives **don't need to broadcast** any of their monitoring data to passives
- Passives **must broadcast any locally-created** monitoring data to the active and **all** passives
- When a **new passive joins the cluster**, each existing passive must **send any locally-created monitoring data** to the new member (which will then pass it to the underlying service)
- When a passive **becomes active**, it can discard any data cached within the _shim_ and disable this caching mechanism

The reason why the passives must cache their locally-created data, within the _shim_, is so that they can re-transmit it to new passives joining the cluster.  Note that this data must either only be sent to the the passive or must be ignored by any others (since they would otherwise see duplicates).

The reason why new passives must receive the existing state of any existing passives is so they know about it, in case they are selected as active, later on (since they would otherwise be missing data from this other passive).  Additionally, if they weren't told the existing structure, they wouldn't be able to update it in response to new data.

**Comment by myronkscott** [comment]
Since the vast majority of cases will be single active and single passive it may not matter, however, what is the value of broadcasting passive state to all passives?  The information is only relevant on the active server so can't the same result be achieved by only broadcasting to the active and passives broadcasting there cache every time a new active takes over?

**Comment by jd0-sag** [comment]
That is also a possible approach (given the current way that we plumb some monitoring data around when an active is elected, this might be a smaller change).  I suspect that the only objective concern is where we want the network traffic to spike and how much ahead-of-time work we want spread to the other passives.

If each passive sends its cache to the new active, when the active has been elected, then it puts the spike at the point of fail-over and reduces the extra work being done by the passives since they don't need to track any other information from the stripe.

If each passive sends its local cache when a new passive joins, then it puts the spike at the point of passive sync and increases the overall chatter across the stripe.

The more I think about your suggestion, the more I am thinking it moves the overhead to a better point, but also the more I think that it is a cleaner approach since it means that passives don't need to work in a "split mode" where they explicitly cache their own data while passing through remote data.  Instead, there would only be an "active mode" where the data is all passed through or "passive mode" where the data is only cached.

I will proceed with the approach you described since it is probably a little simpler to do (I can probably directly co-opt the `PlatformInfoRequest.REQUEST` logic) and keeps the modal operation of the shim clearer.
