### ISSUE TITLE
Provide a mechanism for general query of services state

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#154]
Services need to be able to communicate state information for both monitoring and debugging state dumps.  Provide a mechanism for state dump of services and entities.

**Comment by jd0-sag** [comment]
I am interested in hearing everyone's ideas for how this should work.

Personally, I think that state logging should probably be a serializable key-value put statement, potentially allowing for a transition into some kind of "sub-component state" (probably not exposed as an actual object, since then we would need to define ordering, but some kind of named "enter/exit" calls on the state dump interface).

That way, we could output structured data as either a logical tree of key-value pairs or as a human readable list of information.

We would then need to expose a way to accept this as a quasi-visitor on the high-level component interfaces (entity and service).

Ideally, this could not only solve the state dump problem but could be used for solving problems such as how to query state information from, for example, a passive's service, and then push this structured data into the monitoring tree.  Of course, that assumes that it is sufficient to collect this data only on-demand, and not whenever the service has new information, the way entities can relay this information.

**Comment by jd0-sag** [comment]
Note that this item is effectively the implementation side of this:  https://github.com/Terracotta-OSS/terracotta-apis/issues/67

**Comment by ramsai1729** [comment]
We are going to address this issue in multiple phases, so that we can build basic functionality needed to move system test framework to galvan quickly and enhance the functionality later. 

**Phase 1** 

- Create a Platform built-in service to dump Server state in logs (like existing system test does) so that an entity (like M&M entity) can use this service to dump server state 
- Create an entity that can used by galvan framework to dump the server state 

**Phase 2**

- Extend Services/Entity API, so that platform can request Services/entity to dump their state into logs 
- Extend platform built-in service to dump Services/Entity state into logs 

**Phase 3**

- Add functionality to retrieve Server/Services/Entity state using built-in service instead of just dumping into logs, this can be used by M&M to show cluster state in the TMC/collect cluster state in single place 

I think we can move system-test framework to Galvan after Phase 1, so we can combine Phase 2 & Phase 3 in order to reduce possible API changes. Although we need to discuss with M&M team whether they need functionality mentioned in Phase 3.

**Comment by ramsai1729** [comment]
Phase 2 and Phase 3 are completed in #187. Currently we have LogBasedStateDumper which dumps state into logs. Implementing a StateDumper which can provide platform state to TMS/TMC doesn't need any API changes for Services/Entities. 

Note that StateDumper is an optional API which can be implemented by Services/Entities.
