### ISSUE TITLE
Message transport close takes a long time (5 seconds)

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#159]
It appears to take 5 seconds for the message transport to close (asynchronously).  This means the server side lock manager doesn't notice the a departed connection for 5 seconds, and can end up blocking other connections from interacting with the system (because they are blocked on locks held by that client).

See: https://github.com/chrisdennis/galvan/tree/five-second-pause (BasicEntityInteractionIT)

**Comment by myronkscott** [comment]
When the client says goodbye to the server, it immediately closes its transport layer.  This causes problems on the server side.  Sometimes the goodbye is noticed first and proper closure on the server occur.  Sometimes the EOF from the socket close is noticed first and the server enters a reconnect cycle.  This reconnect cycle ends up in a delay on closure of the connection for a client that will never come back.  Will be fixed by sending the goodbye message and letting the server close the sockets.  The client side will close its sockets based the server side closure.
