### ISSUE TITLE
Create a server package including all dependencies and a run script.

### ISSUE THREAD

**Issue by ramsai1729** [Terracotta-OSS/terracotta-core#21]
After internal discussions, we came up with following structure for server packaging, this issue is for creating a kit with below structure. 

<pre>
server-kit/
      ├── plugins
              ├── api
              └── lib
      ├── legal
      ├── server
              ├── bin
              └── lib
</pre>

**Comment by ljacomet** [comment]
The ascii art does not seem to have worked.

* Why is the server kit dealing with api and api/lib folders?
* What is the plugins folder for?

I believe some more detail is needed to explain how the created structure here will be used as a base for a working setup when used by a client that has to deploy server side entity jars into this server.

**Comment by myronkscott** [comment]
We are working on developer level documentation (entity implementors) in concert with this PR.  To preview answers for you, APIs for services (plugins) need to be separated out from implementation because the API interface must be loaded in the common class loader while we want each service implementation loaded in it's own isolated class loader.  We have designed two methods to accomplish this.  Both have issues but we want to include them both so they can be discussed and come up with a best practice.  Keep in mind, we are trying to accomplish a working model that can be refined after further discussion.  Stay tuned for documentation

**Comment by ramsai1729** [comment]
Fixed ascii art issue.
