### ISSUE TITLE
Error message when starting 3.1.0 server on Windows

### ISSUE THREAD

**Issue by aurbroszniowski** [Terracotta-OSS/terracotta-core#250]
When I start the server from the 3.1.0 kit, the server starts correctly but I get an error message as indicated in the screenshot attached, 

![error plugin](https://cloud.githubusercontent.com/assets/1264251/16502959/2d7e92d4-3f11-11e6-8369-3b18e4230c00.png)

**Comment by myronkscott** [comment]
When plugins directory was moved the new location inside server, the source pointing to the plugins directory [Directories.java](https://github.com/Terracotta-OSS/terracotta-core/blob/master/common/src/main/java/com/tc/config/Directories.java) was not updated to reflect the change.  

This breaks classloader isolation in the server but current downstream consumers are not broken because all services packages **are** included in the base classpath.  

The fix will be to update the referenced file.  Add affirmative logging that the plugins directory has been scanned and write a test confirming the logging.  

Also desirable would be a galvan integration test which purposefully uses classloader isolation.
