### ISSUE TITLE
Killing start-tc-server.sh won't kill the TC server

### ISSUE THREAD

**Issue by henri-tremblay** [Terracotta-OSS/terracotta-core#319]
This happens each time we kill gradle during an integration test for instance.

To reproduce:
```bash
./start-tc-server.sh
kill -9 $PID_OF_SHELL
jps
```
You will see the TC server is still there.

The easiest to fix that would be to add an `exec` in front of the java command.

**Comment by myronkscott** [comment]
exec cannot be used because the script is responsible for restart of the server when it is ZAPPED by the active.

normal kill should transfer the signal and kill the sub-process.  As far as I know, there is no way to handle a kill -9 in this way.  

Jeff may know more but I would classify this as not a bug.

**Comment by jd0-sag** [comment]
As Myron said, it isn't as simple as using an exec since that would undermine the purpose of the script:  implementing the loop to handle the ZAP.

If you look into the history of the file, you are likely to see the previous attempts we had at trying to do this.  First of all, there were too many subtle behavioral variants, depending on the shell.  Even if we were to do that, Myron is right in that it still would never be able to handle -9.

You probably need to see if there is another way to kill the gradle test.

**Comment by henri-tremblay** [comment]
You are right. The -9 example was not a good example. Gradle Ctrl+c is something else. Let me dig a bit to see what is not killing what.
