### ISSUE TITLE
Active sends retire ack to client before entity messenger operations are completed on passive.

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#324]

**Comment by jd0-sag** [comment]
Looking at this, I did see at least 2 issues related to retirement-related calls (the `RetirementManager`, itself, seems fine but the way we call it and use its responses seem off).

To suspected problems (need to be I understand the intent, here, to be sure):

1. `retireForCompletion()` was called before `updateWithRetiree()` which seems wrong since it removes the tracking that the message is currentlyRunning, causing it to always immediately retire
1. We only send the retire messages if the message we completed has a valid return channel to the client.  This is never the case for internally-generated messages (which would be the ones triggering the retire, in these cases)

I will continue investigating into this and will see if we can build some more rigorous tests, internally.
