### ISSUE TITLE
Failed connections are replicated/synced to passive?

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#365]
For an instance, a new connection that times out in waiting for handshake from server gets replicated/synced to passive  This can happen with faulty & slow network during ConnectionFactory.connect() before it returns successful connection. This causes passive to waits for those failed connections to reconnect after failover. 

This issue was sporadically observed with ehcache tests in local environment and related to https://github.com/ehcache/ehcache3/issues/1572.

**Comment by myronkscott** [comment]
I'm not sure if there is much we can do here.  The chain of connections goes from client to active to passive.  If there is even the remote possibility that a client has a message on the wire, either between client and active or active and passive, the passive must know about the connection and wait for reconnect in the case of failover.  This is seen as a timing hole more because the active is killed before it is able to send a cleanup call to the passive.  There may be a way to reduce the hole, but I suspect that it is impossible to completely close the hole.

**Comment by ljacomet** [comment]
I understand closing this race can be an issue. However, would there be a way to make sure it is _closed_ when running in a controlled environment such as Galvan?
Maybe an issue needs to be filed against Galvan for this.

**Comment by myronkscott** [comment]
We will look at this as time permits

**Comment by myronkscott** [comment]
Not observable currently.  If you feel this is in error, please re-open.
