### ISSUE TITLE
Exceptions passed over the wire to clients must not reference server types

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#431]
Currently the EntityConfigurationException constructed on the server has its cause set to the original ConfigurationException (which is only available on the server classpath).  We should avoid situations like this where objects sent over the wire reference types only available on the classpath of the server.  In this case we discussed this and think it's best if rather than chaining the original exception as a cause we instead reskin the original ConfigurationException as an EntityConfigurationException.  Maybe we could just do this via a writeReplace method?

**Comment by jd0-sag** [comment]
It sounds like the `writeReplace` approach should work.  I suspect that we want to replace any exceptions on the server with some sort of "ServerSideExceptionWrapper", or something, so that it doesn't matter what the user code is doing or what other types it might use.

I will experiment with this and see if I can come up with something nice.

**Comment by jd0-sag** [comment]
This will be handled purely on the API-side, related to how the exceptions are serialized:  Terracotta-OSS/terracotta-apis#190
