### ISSUE TITLE
Server crashes when a service isn't found

### ISSUE THREAD

**Issue by henri-tremblay** [Terracotta-OSS/terracotta-core#496]
If a NPE occurs is thrown by `ProxyServerEntityService.createActiveEntity`, the entire server crashes.

This can occur if the client ask for a service that isn't correctly configured on the server. An example is the `EntityMonitoringService` (requested by `NmsEntityServerService`).

**Comment by myronkscott** [comment]
Our current model is to crash on any uncaught exception.  In this sense, the platform works in cooperation with any and all services deployed within.  At some point, we may want to create some isolation level so that some services stay up while other parts of the server are mis-configured or mis-allocated but that is not part of current plans.

**Comment by myronkscott** [comment]
Please close if we have common understanding or elaborate on the issue if you feel something is being missed.  Thanks.
