### ISSUE TITLE
Services must adhere to dirtydb

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#5]
State machine in core is a hold-over from the previous version of the platform.  In that version, storage was directly integrated in the system and the platform could directly clear the persistent data as a result of a dirtydb mark and zap signal.  Going forward, storage will be implemented as a service and storage is no longer directly integrated into platform.  As a result, storage services will need a mechanism to know about dirtydb so that any persistent state can be cleared.

**Comment by jd0-sag** [comment]
Marking ready as we think this should be addressed soon.

There is some question of whether this is a new method on the service interface or whether we need to communicate other platform state/description data to the service, when it is created, which could include information like this.

**Comment by ramsai1729** [comment]
We have discussed two options to solve this issue in last sync up 

1. Add a new method to Service API and platform calls this method on existing services whenever it needs to clear the state 

2. Provide a way for services to query the current state of the platform, so that services can decide when to clear their state 

We need to discuss pros/cons of these two approaches and decide.

**Comment by jd0-sag** [comment]
I would assume that we don't yet know how to implement (2) without it being just over-design so we should probably go with (1) unless we have a really good idea of how we would want to generally expose this information and what kinds of information we could reasonably expose that way (to make sure that we put it in the right place, etc).
