### ISSUE TITLE
Address already in use during transition

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#506]
It is observed sporadically(so far on windows) that server exits with the below error message when transitioning from passive to active,

Server2 - 2017-03-03 10:42:44,305 INFO - Becoming State[ ACTIVE-COORDINATOR ]
Server2 - 
Server2 - 
Server2 - Fatal Terracotta startup exception:
Server2 - 
Server2 -  Uncaught exception in stage.  Please make sure the server isn't already running or choose a different port.
Server2 - 
Server2 - Server startup failed.

**Comment by jd0-sag** [comment]
Do you have any other information regarding this problem?  An exception stack trace in the logs?

We also need to find a way of ruling out actual collisions between multiple servers in the testing environment.

**Comment by esebasti** [comment]
I can provide log when it occurs next time. Since it happens during transition(not on startup), I suspect passive rebinding same tsa port might be causing this problem. But I can double check to rule out collision aspect.

**Comment by jd0-sag** [comment]
Until more information is provided, I am looking into this from the angle of determining if we can reuse the existing socket opened for diagnostic connections (before the server is active) for real client connections (which are available after it becomes active).  Presently, we bring this connection down and create a clean one, when changing state.

I have tried to prototype this change but it is fairly involved since the actual socket bind is done very low in the stack and a great deal of logic is run by the intermediary levels, prior to that bind.  This approach is useful since it eliminates many intermediary states but it means that this port cannot be easily reused without tearing it down and rebuilding it.  This should work reliably but this failure may imply that there are situations where it doesn't.

Hence, we need more information to ensure that there is actually a problem here and allow us to model where/why it happens.  I would still want to spend some time ruling out the possibility that this is an environmental problem prior to undertaking such a large and non-trivial architectural change to the network stack.

**Comment by jd0-sag** [comment]
What kind of test is this (is this in galvan, or something else)?  Do you have the stripe config handy?

I want to rule out any testing environment issues before progressing since, while this diagnostic port isn't very old, it has been in for long enough that I suspect we would have seen this issue earlier.

**Comment by jd0-sag** [comment]
Work-around committed to address this:  55ee59a4416a21fbf475791a9992e95273366f06
