### ISSUE TITLE
MaintenanceModeService needs a better implementation

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#69]
Currently, MaintenenceModeService is not implemented well.  A block in maintenance mode of one entity could block any other entity from getting any mode.  It needs a better implementation that only blocks operations on the target entity.

**Comment by jd0-sag** [comment]
Another way of looking at the problem is in the case of 2 threads accessing different entities over the same connection:  the lock state should be per-thread but it is currently per-connection so one thread blocking will cause another to block, even though it is unrelated.

One could argue that the per-connection approach makes sense but it seems less expected than a per-thread approach.

**Comment by myronkscott** [comment]
It turns out this is not an issue.  Concurrency of the lock mechanism is enough to support multiple entities over the same connection.
