### ISSUE TITLE
PassiveSynchronizationChannel messages jump the queue

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-core#745]
Messages sent down a PassiveSynchronizationChannel do not get enqueued at the back of the queue for a concurrency key, they jump the queue and are sent immediately.

Can we have some discussion as to whether this is correct? It has caused us some problems.

If we are going to consider this correct, then the API javadoc should explain this and present the potential problems (ordering differences between active and passive).

**Comment by ChrisGreenaway** [comment]
Abhilash pointed out that "Its a message added in queue by Voltron to mark the boundary for sync".

To which I'd like to respond that if a message M messages self with M' then M' should perhaps not be able to cross the sync boundary.

**Comment by myronkscott** [comment]
Think of the sync operation on a concurrency key as a member of the linear timeline of messages for that key.  Messages generated in the sync operation are sent directly to the passive so that they are hold the same place in the timeline for that key in relation to messages enqueued both before and after.  Messages sent using messageSelf are just like messages that come from clients and are enqueued at the tail for the concurrency key.  The platform really doesn't have any way of knowing that M and M' are related and therefore can't decide to filter those messages out after sync has occurred for that key.  So it is possible for a message generated before sync to be enqueued behind a sync and replicated to a passive.  I'm not sure there is anything that the platform can do help there.

**Comment by ChrisGreenaway** [comment]
If messages put on to a PassiveSynchronizationChannel were put at the back of the queue then that M and M' issue would go away. Is that not possible? Or does it cause some correctness problem?

**Comment by myronkscott** [comment]
that causes a correctness problem.  You could conceivably do a `messageSelf()` at the end of your `synchronizeKeyToPassive()` providing yourself with a marker in the timeline.  So anything between the sync messages and the marker needs to be filtered by your rules.

**Comment by myronkscott** [comment]
To expand a bit.  The correctness problem is that invokes would start flowing from the active to the passive before the base state for the key is communicated to the passive.  Even worse invokes could be interleaved with sync messages.

**Comment by ChrisGreenaway** [comment]
"invokes would start flowing from the active to the passive before the base state for the key is communicated to the passive" - I agree.

"Even worse invokes could be interleaved with sync messages." - not those sync messages could be added to the back of the queue as an atomic operation. Tricky and anyway irrelevant given the first point.

So I guess we are back to "the API javadoc should explain this and present the potential problems (ordering differences between active and passive)". By this I mean the PassiveSynchronizationChannel API.

**Comment by myronkscott** [comment]
Moving this to an API documentation issue https://github.com/Terracotta-OSS/terracotta-apis/issues/299
