### ISSUE TITLE
java.lang.AssertionError: [0] removeNode(testServer0, platform/clients, 8): unable to remove client: not in current topology

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#802]
@myronkscott @anthonydahanne  : with PR https://github.com/Terracotta-OSS/terracotta-platform/pull/413, the integration tests in another project are failing now with the assertions on with:

```
[FailOverIT][stripe0][testServer0] java.lang.AssertionError: [0] removeNode(testServer0, platform/clients, 8): unable to remove client: not in current topology
[FailOverIT][stripe0][testServer0] 	at org.terracotta.management.service.monitoring.Utils.warnOrAssert(Utils.java:50)
[FailOverIT][stripe0][testServer0] 	at org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter.removeNode(IStripeMonitoringPlatformListenerAdapter.java:188)
[FailOverIT][stripe0][testServer0] 	at com.tc.services.IStripeMonitoringWrapper.removeNode(IStripeMonitoringWrapper.java:59)
[FailOverIT][stripe0][testServer0] 	at com.tc.services.LocalMonitoringProducer.removeNodeFromShim(LocalMonitoringProducer.java:337)
[FailOverIT][stripe0][testServer0] 	at com.tc.services.LocalMonitoringProducer.access$100(LocalMonitoringProducer.java:64)
[FailOverIT][stripe0][testServer0] 	at com.tc.objectserver.core.impl.ManagementTopologyEventCollector.removeClientIfPossible(ManagementTopologyEventCollector.java:270)
[FailOverIT][stripe0][testServer0] 	at com.tc.objectserver.core.impl.ManagementTopologyEventCollector.expectedDisconnects(ManagementTopologyEventCollector.java:249)
[FailOverIT][stripe0][testServer0] 	at com.tc.objectserver.handler.ChannelLifeCycleHandler.notifyEnitiesOfDisconnect(ChannelLifeCycleHandler.java:117)
```
Inside:

`[FailOverIT][stripe0][testServer0] 2017-12-07 19:05:05,818 [WorkerThread(request_processor_stage, 0, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] removeNode(testServer0, platform/clients, 8)`

By looking at the logs, I never see any addNode() call concerning a client 8, and I do not see a double call to `removeNode(testServer0, platform/clients, 8)`

So I think platform did not send us the addNode() event concerning this client.

Is it expected or a bug ?

Could it be related to diagnostic connection ?

**Comment by myronkscott** [comment]
Fixed in 5.4.0-pre13

On Dec 7, 2017, at 4:30 PM, Mathieu Carbou <notifications@github.com<mailto:notifications@github.com>> wrote:


@myronkscott<https://github.com/myronkscott> @anthonydahanne<https://github.com/anthonydahanne> : with PR Terracotta-OSS/terracotta-platform#413<https://github.com/Terracotta-OSS/terracotta-platform/pull/413>, the integration tests in another project are failing now with the assertions on with:

[FailOverIT][stripe0][testServer0] java.lang.AssertionError: [0] removeNode(testServer0, platform/clients, 8): unable to remove client: not in current topology
[FailOverIT][stripe0][testServer0]      at org.terracotta.management.service.monitoring.Utils.warnOrAssert(Utils.java:50)
[FailOverIT][stripe0][testServer0]      at org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter.removeNode(IStripeMonitoringPlatformListenerAdapter.java:188)
[FailOverIT][stripe0][testServer0]      at com.tc.services.IStripeMonitoringWrapper.removeNode(IStripeMonitoringWrapper.java:59)
[FailOverIT][stripe0][testServer0]      at com.tc.services.LocalMonitoringProducer.removeNodeFromShim(LocalMonitoringProducer.java:337)
[FailOverIT][stripe0][testServer0]      at com.tc.services.LocalMonitoringProducer.access$100(LocalMonitoringProducer.java:64)
[FailOverIT][stripe0][testServer0]      at com.tc.objectserver.core.impl.ManagementTopologyEventCollector.removeClientIfPossible(ManagementTopologyEventCollector.java:270)
[FailOverIT][stripe0][testServer0]      at com.tc.objectserver.core.impl.ManagementTopologyEventCollector.expectedDisconnects(ManagementTopologyEventCollector.java:249)
[FailOverIT][stripe0][testServer0]      at com.tc.objectserver.handler.ChannelLifeCycleHandler.notifyEnitiesOfDisconnect(ChannelLifeCycleHandler.java:117)


Inside:

[FailOverIT][stripe0][testServer0] 2017-12-07 19:05:05,818 [WorkerThread(request_processor_stage, 0, 0)] TRACE org.terracotta.management.service.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] removeNode(testServer0, platform/clients, 8)

By looking at the logs, I never see any addNode() call concerning a client 8, and I do not see a double call to removeNode(testServer0, platform/clients, 8)

So I think platform did not send us the addNode() event concerning this client.

Is it expected or a bug ?

Could it be related to diagnostic connection ?

**Comment by mathieucarbou** [comment]
Ok! I'll upgrade in Terracotta-OSS/terracotta-platform#413 then

**Comment by mathieucarbou** [comment]
confirmed I do not see these logs anymore.
