### ISSUE TITLE
EntityUserExceptions are not getting propagated properly on client side 

### ISSUE THREAD

**Issue by ramsai1729** [Terracotta-OSS/terracotta-core#85]
for example, If entity creation is failed on server side for some reason, an EntityUserException is sent back to client but not thrown or passed to user code. 

some relevant code in TerracottaEntityRef.java: 

} catch (EntityException e) {
      // Note that we must externally only present the specific exception types we were expecting.  Thus, we need to check
      // that this is one of those supported types, asserting that there was an unexpected wire inconsistency, otherwise.
      if (e instanceof EntityNotProvidedException) {
        throw (EntityNotProvidedException)e;
      } else if (e instanceof EntityAlreadyExistsException) {
        throw (EntityAlreadyExistsException)e;
      } else if (e instanceof EntityVersionMismatchException) {
        throw (EntityVersionMismatchException)e;
      } else {
        Assert.failure("Unsupported exception type returned to create", e);
      }
    } catch (InterruptedException e) {
      // We don't expect an interruption here.
      throw new RuntimeException(e);

**Comment by jd0-sag** [comment]
We need to decide where it is legal for EntityUserException to be thrown, on the server side, and passed back to the client code without bringing down the server, instead.

In the case of create, we probably can't throw from user code since both the active and passive would need to fail in the same way.

That said, my concern might be purely server-side and this area you are looking at might be purely client-side, which should still decode any exception type and throw it, blindly.

There are relatively few places where the server can throw back EntityUserException (message decode may be the only one), but the client shouldn't enforce a shadow of that rule.

**Comment by ramsai1729** [comment]
this is not an issue anymore as Platform no longer sends EntityUserException to the clients
