### ISSUE TITLE
Provide a way to kill the server

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/terracotta-core#95]
In the current kit, a startup script is provided, and it performs, after setting up the class path, such a command : 

    ${JAVA_COMMAND} -Xms2g -Xmx2g -XX:+HeapDumpOnOutOfMemoryError \
       -Dcom.sun.management.jmxremote \
       -Dtc.install-root="${TC_INSTALL_DIR}" \
       -Dsun.rmi.dgc.server.gcInterval=31536000000\
       ${JAVA_OPTS} \
       -cp "${TC_INSTALL_DIR}/server/lib/tc.jar:${PLUGIN_CLASSPATH}" \
       com.tc.server.TCServerMain "$@"

Thing is, if you start a process with such a command : 

` sh -c /Users/adah/workspaces/management/management-apps-anza/tms/target/voltronTestsHome/terracotta-5.0.0-SNAPSHOT/server/bin/start-tc-server.sh 
`

killing that process, won't kill the voltron JVM...

In TC 4, we used to have a way, based on JMX to kill the server
We could also keep a PID file, or use ``exec`` to start the VM , and then consider the script process the process to destroy to stop Voltron

Anyway, we need a stop-tc-server.sh !

**Comment by mathieucarbou** [comment]
bump.

We cannot use the script within the kit for system tests because it does not use "exec" to start the java process. Exec replaces the current execution by the launched process, keeping the same PID.

I would flag it as a bug because system tests are not possible with such script if we want to make sure the child process is killed with its parent process at the end.

http://stackoverflow.com/questions/18351198/what-are-the-uses-of-the-exec-command-in-shell-scripts

**Comment by jd0-sag** [comment]
The approach that I am using in the testing system, for the moment, is just to manually add the exec to the start script.  This is a work-around but also gives me the ability to test if there are unexpected problems with doing this, since it is a change from previous versions.

Going forward, however, we need a solution which will work on both Windows and Unix systems.  This might mean that we need a way to discover what the command line should be so that we can start it, directly, from test harnesses and other tools.  Either that, or we need a better understanding of what options we have on Windows.

**Comment by mathieucarbou** [comment]
One quick fix that would work for everybody would be to have 2 scripts:

1. start-tc-server.sh
2. start-and-wait-tc-server.sh

I will be exactly like the current script, except that it won't have the while loop, but it will have the exec as the last sentence. Thus, the process exit code would be thrown to the caller.

The second script would only contain the while loop, but will call start-tc-server.sh instead of running a java command.

System tests would be able to use `start-tc-server.sh`

If it is an acceptable solution for you, I can do the PR today.

**Comment by ramsai1729** [comment]
Fixed in issue #115
